### ISSUE TITLE
Error with Poisson example.

### ISSUE THREAD

**Issue by pf4d** [nschloe/pyfvm#21]
I have installed ``pyfvm``, ``voropy``, and ``meshzoo`` from github clones.  When I run your Poisson example, I get the error:

    AttributeError: 'module' object has no attribute 'mesh_tri'

If I instead import ``voropy`` and access ``mesh_tri`` from there, I then get the error:

    ValueError: sort array is read-only

regarding the coordinate array ``m.cells()`` from ``mshr``.  Perhaps you want to copy this instead?

**Comment by nschloe** [comment]
Ah yes, I'll need to update pyfvm for the new voropy interface. I've been meaning to do this for a while now.

**Comment by nschloe** [comment]
Fixed now.
