### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by Cirdans-Home** [nschloe/pyfvm#28]
Hi,

I'm trying to install pyfvm via pip, as suggested in the guide, the procedure ends up with the following error:
`Collecting pyfvm
  Using cached https://files.pythonhosted.org/packages/c4/12/d15678b973cfde5e4fad57abba9023400f82091cd62a0ae3daf0fb43534f/PyFVM-0.2.3-py2.py3-none-any.whl
Collecting voropy (from pyfvm)
  Using cached https://files.pythonhosted.org/packages/62/a7/347577497d12329f4ecb0cb5da7dbc606c414683923f2b56d1078de43340/voropy-0.5.3-py2.py3-none-any.whl
Requirement not upgraded as not directly required: meshzoo in /usr/local/lib/python2.7/dist-packages (from pyfvm) (0.4.1)
Collecting krypy (from pyfvm)
  Using cached https://files.pythonhosted.org/packages/e2/84/8de0afa3d6a969c170c7bafb91d3bd19b29b67c35e4ba53ccf275440f8be/krypy-2.1.7.tar.gz
Requirement not upgraded as not directly required: sympy in /usr/lib/python2.7/dist-packages (from pyfvm) (0.7.6.1)
Collecting sphinxcontrib-bibtex (from pyfvm)
  Using cached https://files.pythonhosted.org/packages/a9/42/54d99325c8d3926a77fec2e898acb60360bff34c31020b0d306c8395b3b9/sphinxcontrib_bibtex-0.4.0-py2.py3-none-any.whl
Collecting code-extract (from pyfvm)
  Could not find a version that satisfies the requirement code-extract (from pyfvm) (from versions: )
No matching distribution found for code-extract (from pyfvm)
`

on the following machine
Linux ASUS-N551JM 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Moreover, I cannot find any repository for the code-extract package on the web.

Thank you very much for your help,

F.D.

**Comment by nschloe** [comment]
Ah yes! I need to update this thing. Give me a moment...

**Comment by nschloe** [comment]
Alright, it's updated now. Let me know if you have any further troubles.

**Comment by Cirdans-Home** [comment]
Hi,

Thank you very much for your fast answer, now it seems that there is a problem with the pybind11 package (I've already tried uninstalling and installing it):

```
/usr/local/include/python2.7/pybind11/pytypes.h:298:12: warning: inline function ‘virtual pybind11::error_already_set::~error_already_set()’ used but never defined
         inline ~error_already_set();
                ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
and at the end:

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-jjP_aF/fastfunc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-re81VL/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-jjP_aF/fastfunc/`

Bests,

F.D.

**Comment by nschloe** [comment]
What you're showing is a warning, not the actual error. (It's typically hard to find in C++ output, look for `error:`.)

(Other than that, I'd recommend using Python 3; Python 2 will reach end of life next year.)
